### ISSUE TITLE
spaCy module must be installed in python

### ISSUE THREAD

**Issue by nujcharee** [statsmaths/cleanNLP#10]
I believe I have successfully installed pre req stuff. I use python 3.5. Once finished installing that I typed >python -c "import spacy; spacy.load('en'); print('OK')" and got OK message back.

After that I went in Rstudio and run init_spaCy() that faile with below message
The spaCy module must be installed in python beforeusing as a backend.

**Comment by taylor-arnold** [comment]
The problem is likely that R is not binding to the version of Python that you installed spaCy with. I just uploaded an updated version of cleanNLP that prints a more helpful error message (including the version of Python that is currently being used). 

If you are still having trouble, please reinstall with `devtools::::install_github("statsmaths/cleanNLP")` and paste the new error message.

**Comment by nujcharee** [comment]
Thank you - i will try this tonight and let you know the result.  Much appreciated.

**Comment by nujcharee** [comment]
Have reinstalled spacy in command line to make sure I got it right. That worked cos I can run import spacy in python at command line and managed to use space.load('en') command

so back to R - I run the following and got error.

difflib <- import("spacy")
Error in py_module_import(module, convert = convert) : 
  TypeError: 'int' object is not callable

Detailed traceback: 
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\spacy\__init__.py", line 8, in <module>
    from . import en, de, zh, es, it, hu, fr, pt, nl, sv, fi, bn, he
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\spacy\en\__init__.py", line 4, in <module>
    from ..language import Language
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\spacy\language.py", line 11, in <module>
    from .train import Trainer
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\spacy\train.py", line 5, in <module>
    import tqdm
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\tqdm\__init__.py", line 1, in <module>
    from ._tqdm import tqdm
  File "C:\Users\nhaswell\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\tqdm\_tqdm.py", line 14, in <module>
    from ._utils import _supports_unicode, _environ_col

Grateful if you could advice please. Thanks so much

**Comment by taylor-arnold** [comment]
Thanks for the more detailed output. If `import("spacy")` is not working, of course **cleanNLP** will not be able to run either, so we need to figure out what the issue is regarding your particular machine. 

Could you post what the output of the following is for you in R (and while you're at it, verify that the 'version' line is what shows up when you start Python):
```
reticulate::py_config()
```
I still think this is likely some miscommunication between which version of Python R is finding; I've run into that `TypeError: 'int' object is not callable` error before when writing code for Python 3 and then having someone test it on Python 3.

**Comment by MathieuMarauri** [comment]
Hello Taylor,

I attended your talks at the useR2017 and there were great, thank you. I really wanted to try your package ever since and now I can. 

I am also having some issues using `init_spaCy()` though.

After installing the dev version of cleanNLP the error message is 

```
Error: The spacy module is not available from the Python
executable located here:

   C:\Users\Mathieu\ANACON~1\python.exe

This can be installed with pip by running the following:

  pip install spacy

If you believe it is already installed, you may be linking 
to the wrong version of Python. See reticulate::use_python()
to set the Python path, then retry. You may need to restart
R before use_python takes effect.
```
`reticulate::py_config()` gives 
```
python:         C:\Users\Mathieu\ANACON~1\python.exe
libpython:      C:/Users/Mathieu/ANACON~1/python36.dll
pythonhome:     C:\Users\Mathieu\ANACON~1
version:        3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Mathieu\ANACON~1\lib\site-packages\numpy
numpy_version:  1.12.1
``` 

I ran the command `use_python()`and it did not throw any error.

Anyway thank you a lot for your presentation at the useR2017. 

Mathieu

**Comment by nujcharee** [comment]
@MathieuMarauri hi there, are you saying you use_python then followed by init_spacy and that works?

**Comment by MathieuMarauri** [comment]
Hello,

I probably mis explained myself. I wanted to say that I also tried using use_python, it dit not throw any error, but things are still not working. 

I am not able to use `init_spaCy()`.

Sorry for the unclear comment.

**Comment by taylor-arnold** [comment]
@MathieuMarauri Sorry for delay in response. it seems that while you have python set up, you have not installed spaCy. Does running this in reticulate give you an error as well:

```{r}
reticulate::import("numpy")
reticulate::import("spacy")
```

**Comment by jaytimm** [comment]
Similar issues as @MathieuMarauri. Running `reticulate::import("spacy")` returns 

`Error in py_module_import(module, convert = convert) : 
  TypeError: 'int' object is not callable`

**Comment by jaytimm** [comment]
For whatever reason, following the Python/spaCy installation instructions (Windows) for the [`spacyr`](https://github.com/kbenoit/spacyr) package sorted my issues out with `cleanNLP::init_spaCy()`.  Using just a basic python installation did the trick.  Something about the path name to Anaconda seems to have been causing problems.    Perhaps this is helpful.

**Comment by taylor-arnold** [comment]
@jaytimm Thanks for the update and glad that worked for you. Will keep this is mind when anyone has trouble on Windows.

**Comment by Sankalikhitha** [comment]
(.env) C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\Scripts>python -m spacy download en
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.



I am getting above error.Please resolve it....

**Comment by Sankalikhitha** [comment]
(.env) C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\Scripts>python -m spacy download en
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.


After installing spacy model,While downloading the spacy en getting the above error.Please can anyone resolve it.

**Comment by wallacemoraes** [comment]
Since the Spacy environment was setup using spacyr you need to start the spacy environment in conda  using spacyr:

`spacy_initialize(save_profile = TRUE)
`

and after, for example:
`cnlp_init_spacy()
`
'reticulate's 'use_python() will not work
