### ISSUE TITLE
Integrate with CoreNLP 3.8

### ISSUE THREAD

**Issue by taylor-arnold** [statsmaths/cleanNLP#14]

**Comment by chris-billingham** [comment]
CoreNLP is up to 3.9.1 so would assume you'd be looking to go to this version. Would it be as easy as replacing the call in the download.R file to [http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip](url) or is that crazy talk?

**Comment by taylor-arnold** [comment]
It takes a little bit more than just changing the paths because the properties file and some of the API points change around between versions. Thankfully this was a relatively simple upgrade compared to the one from 3.5 to 3.7. 

Commit df160a68c0f05700d513ab918115474511477d46 now upgrades to code to the most recent version, CoreNLP 3.9.1.

**Comment by chris-billingham** [comment]
Hurrah!
