### ISSUE TITLE
Every 1000th id has an NA in the tokenized data frame

### ISSUE THREAD

**Issue by marcelbaumgartner** [statsmaths/cleanNLP#18]
Hello, disovering NLP after your wonderful tutorial at UseR 2017! I have a large character vector ( n = 11'260), with texts. When I use run_annotators() on this string, and then do get_combine() on the result, I have NAs in the id field for the 1000th, 2000th, 3000th, ... text. That's a very strange pattern. When i do filter(data, id == 1000), I have NAs in id, but the rest is okay (sid, word, ...). id == 999 is perfect, as well as id == 1001. Why are the id's of multiples of thousands not correctly processed?

To reproduce:
init_tokenizers()
my.char <- rep("This is a strange bug.", 2100)
my.char.anno <- run_annotators(my.char, as_strings = TRUE)
my.char.token <- get_combine(my.char.anno)
filter(my.char.token, id == 1000)
# error here
filter(my.char.token, id == 999)
# okay
filter(my.char.token, id == 1001)

I run R 3.3.2 through RStudio 1.0 on Windows 10. I use version 1.10.0 of "cleanNLP".

Thanks! Marcel

**Comment by taylor-arnold** [comment]
This bug was causing me a headache for quite some time. I finally narrowed
it down to the fact that it only occurs with the tokenizers backend. As the last
commit describes, R was converting 1000 to 1e3, 2000 to 2e3, and so forth.
This is now fixed in the dev version. Thanks for the bug report!
