### ISSUE TITLE
spaCy module must be installed in python #10

### ISSUE THREAD

**Issue by Nayyarkazmi** [statsmaths/cleanNLP#19]
I have been trying to setup cleanNPL using spaCY. I think I have installed everything and got OK messages. But still I get an error when initializing spaCY in R.  Any ideas?

> use_python("C:\\Users\\nayyark\\AppData\\Local\\Continuum\\Anaconda3\\python")

> init_spaCy()
Error in .init_spaCy_backend() : 
  The spaCy module must be installed in python beforeusing as a backend.

Below is the py_config() 

> reticulate::py_config()

python:         C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1\python.exe
libpython:      C:/Users/nayyark/AppData/Local/CONTIN~1/ANACON~1/python36.dll
pythonhome:     C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1
version:        3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\numpy
numpy_version:  1.12.1
spacy:          C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\spacy

python versions found: 
 C:\Users\nayyark\AppData\Local\Programs\Python\Python35\python.exe
 C:\Users\nayyark\AppData\Local\Programs\Python\Python35\\python.exe
 C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\nayyark\AppData\Local\Programs\Python\PYTHON~1\\python.exe
 C:\Users\nayyark\AppData\Local\CONTIN~1\ANACON~1/envs/tensorflow/python.exe

**Comment by Nayyarkazmi** [comment]
Hi I have checked that spacy is installed and I can import it in python, but reticulate::init_spacy() in R gives an error that spacy must be installed in python. py_module_available also return FALSE for spacy, which means it is not available to reticulate. However, py_module_available() returns TRUE for other libraries such as numpy. So it might be something to do with spacy installation or reticulate, I wonder! I have installed spacy through conda. Can you please help me with this?

**Comment by taylor-arnold** [comment]
This was a bug in a previous version of the codebase, where for some reason numpy has to be loaded before spaCy. Should be fixed on the dev version. Will push to CRAN as well soon. If there is still a problem please open a new issue.
