### ISSUE TITLE
  Arabic language is not included in init_coreNLP function 'arg' 

### ISSUE THREAD

**Issue by nesmaAlmoazamy** [statsmaths/cleanNLP#21]
I am trying to use init_coreNLP function with the Arabic language, but I figured out that the Arabic language is not included in the language_list.

Command:
init_coreNLP("ar", anno_level = 2, lib_location = NULL, mem = "6g", verbose = FALSE)
Output:
Error in match.arg(arg = language, choices = language_list) : 
  'arg' should be one of “en”, “de”, “fr”, “es”

**Comment by taylor-arnold** [comment]
The most recent commit, df160a68c0f05700d513ab918115474511477d46, upgrades the library to using coreNLP 3.9.1 and simultaneously now additionally supports parsing text in Chinese and Arabic.
