### ISSUE TITLE
Using cleanNLP and spacy at backend, 'get_coreference' is resulting zero tibble

### ISSUE THREAD

**Issue by rajkshinde** [statsmaths/cleanNLP#24]
Hi,

With any of the tutorial steps below, only 'get_coreference' function is returning no results. All other functions like get_document, get_entity etc are working well.

Tried the obama dataset, get_coreference works well for it. Based on it created a csv file similar to this dataset and created annotated object for it. Again all functions work, except for corefence.
 
Below is the code (same in one of the tutorial):
`library(cleanNLP)` 

> init_spaCy(model_name = "en")
text <- c("The regular early morning yell of horror was the sound of",
          "Arthur Dent waking up and suddenly remembering where he",
          "was. It wasn't just that the cave was cold, it wasn't just",
          "that it was damp and smelly. It was the fact that the cave",
          "was in the middle of Islington and there wasn't a bus due",
          "for two million years.")
text <- paste(text, collapse = " ")
obj <- run_annotators(text, as_strings = TRUE)
get_coreference(obj) 

`A tibble: 0 x 12
 ... with 12 variables: id <int>, rid <int>, mid <int>, mention <chr>,
   mention_type <chr>, number <chr>, gender <chr>, animacy <chr>,
   sid <int>, tid <int>, tid_end <int>, tid_head <int>
` 

**Working function:**
`get_document(obj)`
` A tibble: 1 x 5
     id                time version language
  <int>              <dttm>   <chr>    <chr>
1     1 2017-11-12 14:38:07   2.0.2     <NA>
 ... with 1 more variables: uri <chr>`

Tutorial reference:
1] https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference/A-Tidy-Data-Model-for-Natural-Language-Processing
2] https://github.com/statsmaths/cleanNLP/blob/master/README.md

**Comment by taylor-arnold** [comment]
The spaCy library does not support coreferences, hence why they do note appear. You can see one discussion of this [here](https://github.com/explosion/spaCy/issues/80). There are add-on packages for spacy that provide coreferences, but these do not seem trivial to integrate into a pipeline at the moment.

**Comment by ChengYJon** [comment]
Hi, with huggingface's neural coreference for spacy, is there any chance this might be implemented into cleanNLP's spacy backend?
