### ISSUE TITLE
[Inquiry] Parallel Capability

### ISSUE THREAD

**Issue by iamkbpark** [statsmaths/cleanNLP#25]
Dear Dr. Arnold: First of all, I do appreciate **`CleanNLP `** package and I am taking the full benefit of using it!  This is not an issue and I could not find the place to inquire or pull-request. So please advise where to move and post my message to an appropriate place. 
My question was... 
is there any chance or way to run it (ex. sentiment analysis) with parallel capability(ex. cores = 4)? Since I am an R myopic user with limited coding knowledge only in R, it will be greatly appreciated if I can do it in R with the already fantastic CleanNLP package. Thank you for your time and help! -Sincerely, KB Park

**Comment by taylor-arnold** [comment]
@iamkbpark Running **cleanNLP** in parallel within a single R session is unfortunately not possible at the moment. The spacy and coreNLP backends call Python and Java, respectively. Using many cores would require one or both of these packages to support it. Of course, you could do something on the R side by running **foreach** with an appropriate backend (though I have never personally used rJava or reticulate with foreach, I believe it is possible).
