### ISSUE TITLE
init_spaCy() can't find downloaded model

### ISSUE THREAD

**Issue by pohndorff** [statsmaths/cleanNLP#26]
Hi,

I'm having some trouble running your package. When trying to initialise the SpaCy model for a preferred language `init_spaCy(model_name = "de")` I receive the following error message.

```
Error in value[[3L]](cond) : The model name 'de' cannot be found.
You can generally download models using the following
command in a terminal:

   python -m spacy download de

See the spaCy documentation <https://spacy.io>for more help.
```

I have downloaded the current github version of CleanNLP (1.10.0) and the models for spacy are downloaded as well:

```
    Linking successful
    /Users/phndrff/anaconda3/lib/python3.6/site-packages/de_core_news_sm -->
    /Users/phndrff/anaconda3/lib/python3.6/site-packages/spacy/data/de

    You can now load the model via spacy.load('de')
```

Here's what `py_config` returns:

```
> reticulate::py_config()
python:         /Users/phndrff/anaconda3/bin/python
libpython:      /Users/phndrff/anaconda3/lib/libpython3.6m.dylib
pythonhome:     /Users/phndrff/anaconda3:/Users/phndrff/anaconda3
version:        3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
numpy:          /Users/phndrff/anaconda3/lib/python3.6/site-packages/numpy
numpy_version:  1.13.3
spacy:          /Users/phndrff/anaconda3/lib/python3.6/site-packages/spacy

python versions found: 
 /usr/bin/python
 /usr/local/bin/python
 /Users/phndrff/anaconda3/bin/python
```

Any suggestion how I can make the model visible to CleanNLP?

**Comment by pohndorff** [comment]
Here's more information on my spaCy setup `python -m spacy info --markdown`:

```
* **spaCy version:** 2.0.3
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** de, en, xx
```

**Comment by pohndorff** [comment]
Oddly enough the py_config output changed over the last few restarts of R and I was able to pinpoint the source of my issue.
reticulate was pointing to the wrong python path after restarting and it probably did so internally before. I was able to adapt using `use_python("/Users/phndrff/anaconda3/bin/python", required = TRUE)`.

**Comment by cainesap** [comment]
Hi, Thanks for these comments @pohndorff! In case anyone else comes here looking for an answer to this issue, here's my experience (Mac OS X 10.13.2, R 3.4.3, Python 3.6.2).
I added the following 2 lines to `~/.bash_profile`:
```
RETICULATE_PYTHON='/usr/local/bin/python3'
export RETICULATE_PYTHON
```
Saved the file, opened a new terminal window, started R and all was well when I ran the following commands (whereas previously there had been errors, I think because Py2 was given preference .. but I'd installed SpaCy with Py3):
```
library(reticulate)
py_config()
library(cleanNLP)
cnlp_init_spacy()
```
