### ISSUE TITLE
use_python not changing environment

### ISSUE THREAD

**Issue by fahadshery** [statsmaths/cleanNLP#38]
Hi,

Already looked [here](https://github.com/statsmaths/cleanNLP/issues/10) and can confirm that I have installed anaconda3 as required. When run the `reticulate::use_python("/Users/my_user/anaconda3/bin/python")` and then restarting R is still looking at the old python2.7 that comes preinstalled with macOS.
Here is the config:
`> reticulate::py_config()
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Aug 17 2018, 17:41:52)  [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.0

python versions found: 
 /usr/bin/python
 /Users/my_user/anaconda3/bin/python`

I have installed spacy but its not being picked up because of this reason

**Comment by fahadshery** [comment]
Apologies just solved it by:

`1-reloading RStudio
2-library("reticulate")
use_python("/Users/my_user/anaconda3/bin/python", required = T)`
Before anything else. Check with
`py_config()`

It can load init_spacy now

**Comment by taylor-arnold** [comment]
Excellent. Yes, you need to re-start R for the reticulate functions to pick a different version of Python (this is poorly documented and easily avoided).
