### ISSUE TITLE
Using the coreNLP Backend on Windows, annotate error

### ISSUE THREAD

**Issue by friskin** [statsmaths/cleanNLP#4]
Hi, I am trying to use your cleanNLP package on Windows, with the coreNLP backend.  I believe spaCy is not available on windows, but coreNLP is, so I was hoping to do the analysis using this backend only.

I install the package, as well as download the coreNLP files with no problem.  I try the worked example:

```
library(cleanNLP)
init_coreNLP(speed = 2L)
text <- c("The regular early morning yell of horror was the sound of",
          "Arthur Dent waking up and suddenly remembering where he",
          "was. It wasn't just that the cave was cold, it wasn't just",
          "that it was damp and smelly. It was the fact that the cave",
          "was in the middle of Islington and there wasn't a bus due",
          "for two million years.")
text <- paste(text, collapse = " ")
obj <- annotate(text, as_strings = TRUE, backend = "coreNLP")
```
After running this I get the following error:
```
Error in read_annotation(output_dir) : 
  Cannot find the file "C:\Users\my_usr_name\AppData\Local\Temp\RtmpkVqRcO\file1274cef3299/document.csv"
```
If possible, could someone please have a look at this and see if something is up, or maybe I'm doing something wrong?
Thanks again for a really awesome looking package.

**Comment by ryantsullivan** [comment]
Hey I have the same issue on Windows 10. Let me know if anymore details can help.

**Comment by jjphorn** [comment]
I am using Windows 7 and am having the same issue. I have also tried creating the document.csv in a directory and specified that directory in "out_dir".  This give me the error:

Warning message:
The following named parsers don't match the column names: id, time, version, language, uri 

I add the column names to the document.csv file and then the function runs but when I print "obj" it shows 0 documents:

> obj

A CleanNLP Annotation:
  num. documents: 0

**Comment by taylor-arnold** [comment]
I've been out of town the past two weeks, so apologies for the delay in response. @ryantsullivan  @jjphorn @friskin can you confirm that you have tried this with the latest version of cleanNLP (1.9.0)? There were a lot of internal changes and some of these may fix the problem you are experiencing. I don't have a working Windows 10 install, so cannot duplicate this directly but would like to figure out what the underlying issue is (if it still exists).

**Comment by ryantsullivan** [comment]
Hey! No worries. It is still presenting problems with version 1.9. 

```
Error in read_annotation(output_dir) : 
  Cannot find the file "C:\Users\ryans\AppData\Local\Temp\Rtmp02UQAb\file58b05b2011cc/document.csv"
```
I noticed that the file path uses all back slashes but the final one is a forward slash... That seemed odd to me and I am wondering if that may be part of the problem?

When I try to go to the folder file58b05b2011cc I found it empty but in the parent folder Rtmp02UQAb I found a whole bunch of temp files and 6 csvs named file58b05b2011cccoreference, file58b05b2011ccdependency, file58b05b2011ccdocument, file58b05b2011ccentity, file58b05b2011ccsentence, file58b05b2011cctoken. 

I am wondering if the annotation process is supposed to place these files in the file58b05b2011cc and that is part of the reason why it cannot read the document.csv?

**Comment by jjphorn** [comment]
No worries and thank you for responding. cleanNLP is a fantastic package! I am using version 1.9.0 on windows 7.

**Comment by friskin** [comment]
No worries and thanks for replying!  Yes, unfortunately the problem still persists for me as well with the new version 1.9.0.  Here is my sessionInfo if it helps:
```R
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252    LC_MONETARY=English_South Africa.1252
[4] LC_NUMERIC=C                          LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cleanNLP_1.9.0

loaded via a namespace (and not attached):
[1] readr_1.1.1    compiler_3.4.0 R6_2.2.1       hms_0.3        tools_3.4.0    tibble_1.3.3   Rcpp_0.12.11   rJava_0.9-8    rlang_0.1.1 
```

**Comment by taylor-arnold** [comment]
So it seems that `tempfile()` on Windows returns a path with backslashes, but when running `file.path` on Windows R combines paths using a forward slash. My understanding is that you an use either in Windwos, but probably can't mix that two.

Have any of you tried manually specifying a path to `run_annotators` using a path specified with forward slashes? My guess is that this would work; unfortunately I don't have easy access to a Windows Box right now.

**Comment by ryantsullivan** [comment]
I will try that either today or tomorrow and let you know. Just out of curiosity, why does the spacy annotator not generate the same error?

**Comment by ryantsullivan** [comment]
Hey @statsmaths it is working for me if I specify a filepath with forward slashes or just simply use getwd() since that returns a file path with forward slashes.

**Comment by jjphorn** [comment]
I'm still having the same issue that I described above. When I set "output_dir" to a path specified with forward slashes, I get the error that it cannot find the file "pathISpecify/document.csv". 

@ryantsullivan Your's is working?

**Comment by taylor-arnold** [comment]
This seems to be a problem with mixing forward and backward slashes in path names. On Windows it is possible to use either, however the difficulty is that my code needs to take your input path and construct paths to files *within* that path so I need to figure out what path separator to use. This seems to be harder than one would think.

I just pushed an update to cleanNLP (1.9.1; 728db23457b15b27f07830dfcbd513063dace58c) that now modifies the `output_path` to convert all backslashes to forward-slashes. As mentioned above, I still won't have a working R installation for a few weeks (annoying, right after I return from useR! 2017).  If possible, I would appreciate knowing if this fixes the problem or produces any other unintended consequences.

**Comment by ryantsullivan** [comment]
@jjphorn Yes, prior to this current update this worked for me:

```library(tidyverse)
library(magrittr)
library(cleanNLP)

init_coreNLP(mem = "12g" ,language = "en", anno_level = 2, 
             lib_location = "C:/CoreNLP/stanford-corenlp-full-2016-10-31", 
             verbose =  TRUE)

gas_concerns_annotation_test <- gas_text_concerns %>%
    select(Answer) %$%
    cleanNLP::run_annotators(Answer, as_strings = TRUE, doc_id_offset = 1, output_dir = getwd(), load = TRUE)
```

@statsmaths After updating to 1.9.1 this does not work:

```library(tidyverse)
library(magrittr)
library(cleanNLP)

init_coreNLP(mem = "12g" ,language = "en", anno_level = 2, 
             lib_location = "C:/CoreNLP/stanford-corenlp-full-2016-10-31", 
             verbose =  TRUE)


mt_concerns_annotation <- mt_text_concerns %>%
    select(Answer) %$%
    cleanNLP::run_annotators(Answer,as_strings = TRUE, doc_id_offset = 1)
```

Error message:  Error in read_annotation(output_dir) : 
  Cannot find the file "C:/Users/ryans/AppData/Local/Temp/RtmpUViOTP/file54203c284ada/document.csv"

So it is now showing a correct file path but the files are not there they actually seem to be in a temporary state  and located here: 
"C:/Users/ryans/AppData/Local/Temp/RtmpUViOTP/"

The files are all prefixed like this:
file54203c284adadocument.csv
file54203c284adadependency.csv
etc...

This method still works with the update:
```library(tidyverse)
library(magrittr)
library(cleanNLP)

init_coreNLP(mem = "12g" ,language = "en", anno_level = 2, 
             lib_location = "C:/CoreNLP/stanford-corenlp-full-2016-10-31", 
             verbose =  TRUE)


mt_concerns_annotation <- mt_text_concerns %>%
    select(Answer) %$%
    cleanNLP::run_annotators(Answer,as_strings = TRUE, doc_id_offset = 1, output_dir = getwd())
```

Let me know if you have any questions or need any more information.

Thanks for working on it!

**Comment by jjphorn** [comment]
@ryantsullivan 
I just tried using the current version 1.9.1 as well as experienced the exact same problem as you.

**Comment by ryantsullivan** [comment]
@jjphorn have you tried setting the output_dir to something like getwd()? While not ideal its a working work-around for me.

**Comment by davefrancis** [comment]
Changing line 105 of `annotate.R` to: `output_dir <- file.path(Sys.glob(output_dir), "/")` got the file name prefixing issue resolved on my Windows 10 machine.

**Comment by taylor-arnold** [comment]
@davefrancis Thank you so much for the suggestion. I just modified that line and pushed to GitHub. If you get a chance, please verify that this fixes the problem.

Oddly enough, `file.path(Sys.glob(output_dir), "/")` seems to have a different behaviour on Windows as it does on Linux and macOS (in the latter, a leading "/" is appended to the path). Quite strange!

**Comment by jjphorn** [comment]
Awesome, it now works for me! 

@statsmaths  - I noticed that when I update cleanNLP to the latest GitHub version, I have to re-run download_core_nlp(). Is there a way to avoid re-downloading the java files each time an update is performed?

**Comment by taylor-arnold** [comment]
Excellent, glad to have finally fixed this problem. I'm closing this issue now and plan to push a new version to CRAN over the weekend. If anyone else sees this and has a similar problem, please open a new issue.

@jjphorn When you run `download_core_nlp`, the default installation location is the directory where the package is installed. When you re-install the package this is wiped out, causing you to have to redownload the java files each time. You can instead change the parameter `output_loc` to download the files somewhere else on your machine; this will not get overwritten, but you will need to pass the option `lib_location` each time you call `init_coreNLP` with the path to java files as otherwise the package will not know where to find them.
