### ISSUE TITLE
Visualize Parse Tree Structures with cleanNLP

### ISSUE THREAD

**Issue by GreyMerchant** [statsmaths/cleanNLP#41]
Good day,

Is there an easy way to use cleanNLP's output to generate a parse tree structure? 

Sorry in advance if this is a noobish question - I did look on a variety of places and I didn't have any luck.

Kind regards

**Comment by taylor-arnold** [comment]
The parse tree information is available in the annotation output, but a specific built-in visualization is not available in the package.
