### ISSUE TITLE
get_combine() function no longer available?

### ISSUE THREAD

**Issue by fahadshery** [statsmaths/cleanNLP#42]
Hi,

Following your tutorial [here](https://github.com/statsmaths/useR2017_nlp/blob/master/topic01.pdf).
I can't seem to get `cnlp_get_combine()` or `get_combine()`. is it being removed/deprecated? 

thanks
Fahad

**Comment by taylor-arnold** [comment]
Yes, you should now just use `cnlp_get_token` with the option `combine=TRUE`. 
I realized there was no reason to have a separate function. Thanks for reminding me
about those tutorial slides. I'll put on my to-do list updating that with the new function
calls.
