### ISSUE TITLE
Spacy Backend Neural Coreference?

### ISSUE THREAD

**Issue by chengyjonathan** [statsmaths/cleanNLP#44]
Hello, this is an awesome library.

I was curious whether spacy's neural coreference would be added to the spacy backend (https://github.com/huggingface/neuralcoref). This is more of a wishlist comment than an issues one. Apologies, and thank you!

**Comment by taylor-arnold** [comment]
Thanks for the suggestion. I know this was an old post, I have had the goal of 
incorporating this in as a long-term plan but haven't had the time. I just
released a new version of the toolkit (3.0.0) that should make it easier to
integrate other Python libraries into the kit. I was hoping the NeuralCoref
would start supporting other languages, but even English would be helpful
for a lot of people.
