### ISSUE TITLE
Encoding issue while annotating a sentence in Spanish with stanford-corenlp backend

### ISSUE THREAD

**Issue by martinolmos** [statsmaths/cleanNLP#49]
I'm trying to annotate a sentence in Spanish with cleanNLP and stanford-corenlp backend. When I inspect the output tokens I notice that all non-ascii characters were removed and the words with these characters were splited.

Here is a repoducible example:

```r
> library(cleanNLP)
> 
> cnlp_init_corenlp(
+   language = "es", 
+   lib_location = "C:/path/to/stanford-corenlp-full-2018-10-05")
Loading required namespace: rJava
> 
> input <- "Esta mañana desperté feliz."
> 
> Encoding(input)
[1] "latin1"
> 
> input <- iconv(input, "latin1", "UTF-8")
> 
> Encoding(input)
[1] "UTF-8"
> 
> myannotation <- cleanNLP::cnlp_annotate(input)
> 
> myannotation$token$word
[1] "ROOT"    "Esta"    "ma"      "ana"     "despert" "feliz"   "."
```

Session info:

```r
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Argentina.1252  LC_CTYPE=Spanish_Argentina.1252   
[3] LC_MONETARY=Spanish_Argentina.1252 LC_NUMERIC=C                      
[5] LC_TIME=Spanish_Argentina.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cleanNLP_2.3.0

loaded via a namespace (and not attached):
[1] compiler_3.6.0    tools_3.6.0       textreadr_0.9.0   data.table_1.12.2
[5] knitr_1.22        xfun_0.6          rJava_0.9-11      XML_3.98-1.19    
> 
```

**Comment by taylor-arnold** [comment]
I don't have a windows machine to check this directly, but I believe the issue is
the default encoding on your machine. If you run this prior to annotating the code
to set the default encoding there is a good chance that will fix the issue:

```{r}
options(encoding="UTF-8")
```

You could also try saving the text as a file directly (with the proper encoding)
and passing in the file names. Or, just use one of the other backends... spacy and
udpipe should run fine.

**Comment by martinolmos** [comment]
Your first solution worked perflectly. Thank you very much for your answer and for the package.
