### ISSUE TITLE
Error when specifying output location to download coreNLP function

### ISSUE THREAD

**Issue by davefrancis** [statsmaths/cleanNLP#6]
When specifying an `output_loc` to the `download_core_nlp()` function, I receive the following error when the folder doesn't exist:
```
Error in RCurl::CFILE(fp, mode = "wb") : 
  Cannot open file C:/Users/davefrancis/non-existant-folder-name//stanford-corenlp-full-2016-10-31.zip
```
Would be nice for it to create the folder, or generate a more descriptive error.

**Comment by jjphorn** [comment]
@statsmaths Is this fixed in the latest release? I just installed cleanNLP Version 1.10.0 and I received the same error when I ran the `download_core_nlp()` function.

**Comment by taylor-arnold** [comment]
Yes, I believe it is (that is, it produces a better warning; I don't want to create the directory if it doesn't exist).

When I run the following:
```
download_core_nlp(output_loc = "/really/nothing/here")
```
I get the error:
```
Error in download_core_nlp(output_loc = "/really/nothing/here") : 
  The output directory '/really/nothing/here' does not exist
```
Are you still getting an error at the **RCurl** level?

**Comment by jjphorn** [comment]
Yes, it is at the RCurl level. Here is the error.

`Error in RCurl::CFILE(fp, mode = "wb") : 
  Cannot open file C:/Desktop/Research/r/cleanNLP/extdata//stanford-corenlp-full-2016-10-31//stanford-english-corenlp-2016-10-31-models.jar
In addition: Warning messages:
1: In utils::unzip(file.path(output_loc, paste0(coreFile, ".zip")),  :
  error 1 in extracting from zip file
2: In file.remove(file.path(output_loc, paste0(coreFile, ".zip"))) :
  cannot remove file 'C:/Desktop/Research/r/cleanNLP/extdata//stanford-corenlp-full-2016-10-31.zip', reason 'No such file or directory'`

**Comment by jjphorn** [comment]
@statsmaths  FYI - I tried this on my mac laptop and received the same error so it doesn't appear to be OS based.

**Comment by joshuaulrich** [comment]
The problem is that you did not specify the `.zip` extension on [line 93](https://github.com/statsmaths/cleanNLP/blob/6582dbedf1f7d34576db1e58f212c8e34e43fd12/R/download.R#L93), and possibly [line 65](https://github.com/statsmaths/cleanNLP/blob/6582dbedf1f7d34576db1e58f212c8e34e43fd12/R/download.R#L65).

That means you download the zip file correctly, but you save it in a file with no extension.  Then you try to access a file that has the same name but with the .zip extension.  That file doesn't exist, so you get an error.

**Comment by davefrancis** [comment]
@joshuaulrich  the `.zip` extension was removed from those lines to fix [this issue](https://github.com/statsmaths/cleanNLP/issues/7). Perhaps the solution is to add the extension after the existence check of file path (line 93), but before it is downloaded by RCurl.

I am using v1.10.0 on Windows 10 and the download and unzipping behaviour works as expected.

**Comment by joshuaulrich** [comment]
Thanks for the pointer to the prior issue.  My patch would re-introduce that bug.

> I am using v1.10.0 on Windows 10 and the download and unzipping behaviour works as expected.

I don't see how that's possible when using the default arguments to `download_clean_nlp()` from a fresh install of cleanNLP.  Calling the function with its default arguments does not work for me using v1.10.0 on 64-bit Windows 7, 64-bit Ubuntu 16.04, and didn't work for @jjphorn on some version of Windows and MacOS.

Here's the output from stepping through the `download_clean_clp()` function during a fresh install of cleanNLP from CRAN.

```
F:\git\R>R --quiet
> install.packages("cleanNLP")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/cleanNLP_1.10.0.zip'
Content type 'application/zip' length 3569363 bytes (3.4 MB)
downloaded 3.4 MB

package 'cleanNLP' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Josh\AppData\Local\Temp\RtmpOwPVuR\downloaded_packages
> debugonce(cleanNLP::download_core_nlp)
> cleanNLP::download_core_nlp()
debugging in: cleanNLP::download_core_nlp()
debug: {
<snip>
Browse[2]>
debug: if (type %in% c("default", "base")) {
    fp <- .check_file_exists(file.path(output_loc, coreFile),
        force = force)
    f <- RCurl::CFILE(fp, mode = "wb")
    ret <- RCurl::curlPerform(url = paste0(baseURL, coreFile,
        ".zip"), writedata = f@ref, noprogress = FALSE)
    RCurl::close(f)
    if (ret != 0)
        stop("Download error!")
    utils::unzip(file.path(output_loc, paste0(coreFile, ".zip")),
        exdir = output_loc)
    file.remove(file.path(output_loc, paste0(coreFile, ".zip")))
    ret <- 0L
}
Browse[2]>
debug: fp <- .check_file_exists(file.path(output_loc, coreFile), force = force)
Browse[2]>
debug: f <- RCurl::CFILE(fp, mode = "wb")
Browse[2]> fp
[1] "E:/R/R-3.4.1/library/cleanNLP/extdata//stanford-corenlp-full-2016-10-31"
Browse[2]>
debug: ret <- RCurl::curlPerform(url = paste0(baseURL, coreFile, ".zip"),
    writedata = f@ref, noprogress = FALSE)
Browse[2]>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  370M  100  370M    0     0  2809k      0  0:02:15  0:02:15 --:--:-- 3036k
debug: RCurl::close(f)
Browse[2]>
debug: if (ret != 0) stop("Download error!")
Browse[2]> dir(output_loc)
 [1] "cleanNLP-0.1.jar"
 [2] "CoreNLP-to-HTML.xsl"
 [3] "stanford-corenlp-full-2016-10-31"
 [4] "StanfordCoreNLP-arabic.properties"
 [5] "StanfordCoreNLP-chinese.properties"
 [6] "StanfordCoreNLP-english-all.properties"
 [7] "StanfordCoreNLP-english-fast.properties"
 [8] "StanfordCoreNLP-french.properties"
 [9] "StanfordCoreNLP-german.properties"
[10] "StanfordCoreNLP-spanish.properties"
[11] "StanfordCoreNLP.properties"
Browse[2]> file.exists(file.path(output_loc, paste0(coreFile, ".zip")))
[1] FALSE
Browse[2]> utils::unzip(file.path(output_loc, paste0(coreFile, ".zip")), exdir$
Warning message:
In utils::unzip(file.path(output_loc, paste0(coreFile, ".zip")),  :
  error 1 in extracting from zip file
```


> Perhaps the solution is to add the extension after the existence check of file path (line 93), but before it is downloaded by RCurl.

A better solution would be to use `dir.exists()` to check for the existence of a directory instead of relying on the implicit behavior of `file.exists` returning `TRUE` for directories also.  That makes the intent of the code much clearer.  Using the name `coreFile` for a directory is also confusing.

**Comment by davefrancis** [comment]
@joshuaulrich After trying this again with the default arguments, I am getting that same error. My apologies for the confusion, I think I had a cached .zip file in my output directory. I agree that using `dir.exists()` makes the code clearer in its intent.

**Comment by joshuaulrich** [comment]
@davefrancis thanks for the feedback!  I just pushed an update that should solve the missing .zip extension issue without undesired side-effects.

**Comment by taylor-arnold** [comment]
Thanks for the update. I just pushed it in without a problem. Please open a new issue if this does not solve the problem (note that you need to download the dev version from GitHub for this to take effect as it is not yet on CRAN).
