### ISSUE TITLE
Error with corenlp when text document contains underscores

### ISSUE THREAD

**Issue by maelick** [statsmaths/cleanNLP#63]
I upgraded to cleanNLP 3.0, and now my existing code is broken.

When running:
`cleanNLP::cnlp_annotate("Test _somewhere_ test, test.", backend = "corenlp")`

I get the following error:
`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0`

**Comment by taylor-arnold** [comment]
Thanks for the information. For some reason, the new Python backend returns a NoneType
when given some characters (such as an underscore). I just pushed an update that fixes the
issue, but note that it requires updating to the current GitHub version of the R package AND
the Python package. You can do that by running this in R:

```{r}
devtools::install_github("statsmaths/cleanNLP")
```

And these in a terminal:

```{r}
git clone https://github.com/statsmaths/cleanNLP-python
cd cleanNLP-python
python -m pip install .
```

If the two versions are out-of-sync, you will probably get an error about the number of arguments.
Please let me know if this does not solve the problem or you find anything else with the new
version of the package.

**Comment by maelick** [comment]
Thanks, it now works :-)
