### ISSUE TITLE
CoreNLP considerably slower with cleanNLP 3.0

### ISSUE THREAD

**Issue by maelick** [statsmaths/cleanNLP#64]
My existing code relying on the CoreNLP backend used to tokenize and perform POS tagging of 36000 text documents in ~40s. With cleanNLP 3.0, after 4 minutes, only 200 documents are processed.

One possible reason for this is that with cleanNLP 2.3 I was initializing CoreNLP as such as I didn't need anything else than tokenization and POS tagging:
`cnlp_init_corenlp("en", anno_level=0)`

Is there a way to pass this annotation level to CoreNLP with the 3.0 release?

**Comment by taylor-arnold** [comment]
Well, it should be possible now with the new version of the package (and after the fix I pushed
regarding your other issue #63) to select only a subset of the annotators. As in #63, you need
to updating to the current GitHub version of the R package AND the Python package. You can do that by running this in R:

```{r}
devtools::install_github("statsmaths/cleanNLP")
```

And these in a terminal:

```{r}
git clone https://github.com/statsmaths/cleanNLP-python
cd cleanNLP-python
python -m pip install .
```

Then, you should be able to control what annotators to use like this:

```
cnlp_init_corenlp(config=list('processors'='tokenize,mwt,pos,lemma'))
```

I am running some benchmarks right now to see how this effects the speed and will post once these are done.

**Comment by taylor-arnold** [comment]
I ran cleanNLP with various set-ups on the first 25 State of the Union Addresses. Here are the timings using coreNLP with various settings:

```
library(cleanNLP)
library(sotu)


cnlp_init_corenlp(config=list('processors'='tokenize,mwt,pos,lemma,depparse'))
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 3.775241 mins

cnlp_init_corenlp(config=list('processors'='tokenize,mwt,pos,lemma'))
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 1.485189 mins

cnlp_init_corenlp(config=list('processors'='tokenize'))
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 36.4162 secs
```

Turning off parsing speeds up by about a factor of 2; turning off POS tags speeds it up by another factor of 3. However, looking at detecting POS tags with UDPipe and spacy seems to be faster:

```
cnlp_init_udpipe(parser='none')
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 38.52161 secs

cnlp_init_spacy(disable=c('parser', 'ner'))
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 3.161457 secs
```

The udpipe backend is about 3 times faster, but spacy is more than an order of magnitude faster. Even when turning on parsing and NER the speed is very fast:

```
cnlp_init_spacy()
t1 <- Sys.time()
z <- cnlp_annotate(sotu_text[1:25])
t2 <- Sys.time()
t2 - t1 # Time difference of 11.28788 secs
```

So, if you are interested in speed I would suggest using spacy. I am not sure why the Python CoreNLP, POS-only code is so much slower, but that's something that you should bring up with the Stanford CoreNLP developers (unless you have some benchmark showing that it is all due to CleanNLP overhead, but that seems unlikely as it would apply equally to the other backends).

**Comment by maelick** [comment]
The reason why I use CoreNLP, in this case, is because I need to compare tokens with tokens that were obtained by other people with CoreNLP. While the config parameter available in the development version of cleanNLP speed up my existing code significantly (1000 documents are now processed in ~40s), it is still significantly slower than with cleanNLP 2.3.

For example with your example with the state of the union I get the followings:

With cleanNLP 3.0:
`> library(cleanNLP)
> cnlp_init_corenlp(config=list('processors'='tokenize'))
> system.time(cnlp_annotate(sotu::sotu_text[1:25]))
   user  system elapsed 
151.176   0.882 144.550`

With cleanNLP 2.3:
`> library(cleanNLP)
> cnlp_init_corenlp("en", 0)
> system.time(cnlp_annotate(sotu::sotu_text[1:25]))
   user  system elapsed 
  9.070   0.000   3.654`

**Comment by maelick** [comment]
Looking at the code of both cleanNLP 2.3 and 3.0, I'm guessing the difference comes from the Java implementation of CoreNLP used previously that is faster than the pure Python one used now.

**Comment by taylor-arnold** [comment]
Yes, that is the difference. It had become too much to try to keep up with the Java-based
CoreNLP backend (it took up most of my time supporting CleanNLP, and I don't actually
think it is a very good option for most people). Generally, if you need speed, use spacy.
If you need a lot of languages and/or and easy installation, use UDPipe.
