### ISSUE TITLE
Does it support quote attribution?

### ISSUE THREAD

**Issue by mirfan899** [statsmaths/cleanNLP#65]
I'm trying to get quote attribute for documents but I think it does not support it yet
https://stanfordnlp.github.io/CoreNLP/quote.html#quote-attribution

**Comment by BvdM0** [comment]
Bump! This is also my issue right now

**Comment by taylor-arnold** [comment]
No, I don't think the quote annotation is available yet in the Python backend. I just
opened an issue to see what there plans are for supporting this:

- [Differences with Java #163](https://github.com/stanfordnlp/stanfordnlp/issues/163)

**Comment by taylor-arnold** [comment]
Okay, from the post on the CoreNLP page it seems that NER will be supported soon but coreferences and quote attribution is not in the current workplan. It seems like this Python library, which is built on top of spacy, offers quote attribution in addition to some other high-level tasks:

     https://github.com/chartbeat-labs/textacy

It is also quite popular. Any experience with this @mirfan899 and @BvdM0 ? I would really like to support more high-level NLP tasks through Python.
