### ISSUE TITLE
[Inquiry] corenlp backend sentiment score question

### ISSUE THREAD

**Issue by GDawgg** [statsmaths/cleanNLP#67]
when using cleanNLP to annotate files with the coreNLP backend, the sentiment scores return with NA. I downloaded the github version of coreNLP using devtools::install_github('statsmaths/coreNLP'), restarted R and no change. Does cleanNLP no longer support sentiment scoring?

My machine is using: R 3.6.1, RStudio 1.2.5019, cleanNLP version 3.0.0, coreNLP version 0.4-3, Windows 10. .
thx!

**Comment by taylor-arnold** [comment]
I am confused. You posted on two different project's issues (cleanNLP and coreNLP) and I cannot figure out which one you are using. They are different packages and are not linked together. If you are using coreNLP, it should still support sentiment analysis. The cleanNLP package's backend does not support sentiment analysis. If you would like sentiment/polarity analysis, I would suggest lemmatising with cleanNLP and joining with a tagged lexicon of terms (see [The MPQA Opinion Corpus](http://mpqa.cs.pitt.edu/lexicons/) for one example).

**Comment by GDawgg** [comment]
I’m using both, but I realize now that my question wasn’t clear. I thought that at one point in the past that cleanNLP supported sentiment scoring, maybe I am wrong about this. I will spend some more time clarifying my question for coreNLP and post it there. Sorry for the confusion.
